/**
 * Per-environment settings — the one file to edit when an environment changes.
 *
 * Two environments, one per long-lived git branch:
 *
 *   dev   <- branch `develop`  (where changes land first)
 *   prod  <- branch `main`     (only what was merged from develop)
 *
 * Nothing here is secret: this repo is public, and every value below is
 * either a public URL or a cost/safety knob. Secrets (the DB password) are
 * generated by CDK into Secrets Manager and never appear in code.
 */

export type Stage = 'dev' | 'prod'

export interface StageConfig {
  /** Git branch that deploys this environment through GitHub Actions. */
  branch: string

  /**
   * How the private Lambda reaches the internet (Secrets Manager, S3, the
   * Cognito JWKS and admin API):
   *   instance  a t4g.nano NAT instance, ~US$3/month. Not auto-healing: if it
   *             dies the API cannot reach Secrets Manager until it is replaced.
   *   gateway   the managed NAT gateway, ~US$32/month. Highly available.
   */
  nat: 'instance' | 'gateway'

  /**
   * Origins allowed to call the API from a browser. The Amplify URL of the
   * branch goes here once the Amplify app exists — see DEPLOYMENT.md.
   */
  frontendOrigins: string[]

  /** Where CloudWatch alarms (API errors, DB storage) are emailed. */
  alarmEmail: string
}

export const STAGES: Record<Stage, StageConfig> = {
  dev: {
    branch: 'develop',
    nat: 'instance',
    frontendOrigins: [
      // Lets `npm run dev:aws` in proyectos-frontend call the deployed dev API.
      'http://localhost:5173',
    ],
    alarmEmail: 'oasi-ti@economia.cl',
  },
  prod: {
    branch: 'main',
    nat: 'gateway',
    frontendOrigins: [],
    alarmEmail: 'oasi-ti@economia.cl',
  },
}

/** Account-wide settings, deployed once by hand (Oasi-Account stack). */
export const ACCOUNT = {
  githubOrg: 'OASI-CL',
  githubRepo: 'proyectos-backend',
  /** Monthly spend that triggers a budget email (US$). Expected total ~70. */
  monthlyBudgetUsd: 100,
  budgetEmail: 'oasi-ti@economia.cl',
}

export function stageConfig(stage: string): StageConfig {
  if (stage !== 'dev' && stage !== 'prod') {
    throw new Error(`Unknown stage "${stage}". Use -c stage=dev or -c stage=prod.`)
  }
  return STAGES[stage]
}
