import { DeleteObjectCommand, GetObjectCommand, S3Client } from '@aws-sdk/client-s3'
import { pool } from '../db/client'
import { baselineMigrations, runMigrations } from '../db/migrate'

/**
 * db-ops Lambda: the only way anything outside the VPC touches the database.
 *
 * RDS sits in isolated subnets with no public address, so instead of opening
 * a tunnel, this function runs inside the VPC and does the few operational
 * tasks that need direct access. It has no HTTP endpoint; it can only be
 * invoked with IAM credentials (the GitHub deploy role, or an admin's CLI).
 *
 *   {"action":"status"}                          applied migrations + row counts
 *   {"action":"migrate"}                         see src/db/migrate.ts
 *   {"action":"check-isolation"}                 proves this environment's
 *                                                credentials cannot open the
 *                                                other environment's database
 *   {"action":"load-data","key":"ops/x.sql"}     LEGACY one-time load of a pg_dump
 *                                                into an empty database. Replaced
 *                                                by apply-sql (its script,
 *                                                load-data.sh, was removed)
 *   {"action":"apply-sql","key":"ops/x.sql"}     runs a SQL file generated by
 *                                                db/seed_catalogos.py or
 *                                                db/cargar_excel.py (the regular,
 *                                                incremental Excel load). Unlike
 *                                                load-data it runs on a database
 *                                                that already has data: those
 *                                                files only INSERT ... ON CONFLICT.
 *   {"action":"wipe-data","confirm":true}        DESTRUCTIVE: empties every data
 *                                                table (not catalogs, not
 *                                                usuarios) so a load can start
 *                                                from scratch
 *   {"action":"create-admin","sub":"…","email":"…","nombre":"…"}
 *
 * Wrapped by npm run db:* (scripts/db.ts), scripts/aplicar-sql.sh,
 * scripts/create-admin.sh.
 * A thrown error surfaces as a failed invocation, which makes those scripts
 * and the CI step exit non-zero.
 */

type DbOpsEvent =
  | { action: 'status' }
  | { action: 'migrate' }
  | { action: 'baseline'; hasta: string }
  | { action: 'check-isolation' }
  | { action: 'load-data'; key: string }
  | { action: 'apply-sql'; key: string }
  | { action: 'wipe-data'; confirm: boolean }
  | { action: 'create-admin'; sub: string; email: string; nombre: string }

/**
 * Tables the Excel load fills (db/cargar_excel.py). Catalogs are loaded by
 * db/seed_catalogos.py; usuarios and the rest belong to each environment.
 */
const DATA_TABLES = ['empresas', 'titulares', 'proyectos', 'permisos', 'comites', 'permisos_comite']

let s3: S3Client | null = null

export async function handler(event: DbOpsEvent) {
  switch (event.action) {
    case 'status':
      return status()
    case 'migrate':
      return runMigrations(pool)
    case 'baseline':
      return baselineMigrations(pool, event.hasta)
    case 'check-isolation':
      return checkIsolation()
    case 'load-data':
      return loadData(event.key)
    case 'apply-sql':
      return applySql(event.key)
    case 'wipe-data':
      return wipeData(event.confirm)
    case 'create-admin':
      return createAdmin(event)
    default:
      throw new Error(`Unknown action: ${JSON.stringify(event)}`)
  }
}

async function status() {
  const tracking = await pool.query("SELECT to_regclass('public._migrations') IS NOT NULL AS exists")
  const migrations = tracking.rows[0].exists
    ? (await pool.query('SELECT nombre, aplicada_at FROM _migrations ORDER BY nombre')).rows
    : []

  const hasSchema = (await pool.query("SELECT to_regclass('public.proyectos') IS NOT NULL AS exists")).rows[0].exists
  const counts: Record<string, number> = {}
  if (hasSchema) {
    for (const table of [...DATA_TABLES, 'usuarios', 'adjuntos', 'historial', 'solicitudes_cambio']) {
      // A table may not exist yet on a database behind on migrations
      // (titulares arrived in 0008): report it as missing instead of failing.
      const exists = (await pool.query('SELECT to_regclass($1) IS NOT NULL AS e', [`public.${table}`])).rows[0].e
      counts[table] = exists ? (await pool.query(`SELECT count(*)::int AS n FROM public.${table}`)).rows[0].n : -1
    }
  }
  return { migrations, counts }
}

/**
 * Prueba, de verdad, que las credenciales de ESTE ambiente no puedan abrir la
 * base de los otros. No alcanza con haber corrido los REVOKE: esto intenta la
 * conexión y espera que falle.
 *
 * `npm run db:check -- --env=dev`
 */
async function checkIsolation() {
  const others = (process.env.OTHER_DATABASES ?? '').split(',').map((s) => s.trim()).filter(Boolean)
  if (!others.length) return { checked: [], note: 'No hay otras bases en este servidor' }

  // Las credenciales salen del mismo lugar que usa la app, así que esto prueba
  // exactamente lo que pasaría si alguien usara este ambiente para llegar al otro.
  const { Client } = await import('pg')
  const checked: { database: string; connected: boolean; error?: string }[] = []

  for (const database of others) {
    const client = new Client({
      host: process.env.DB_HOST,
      port: process.env.DB_PORT ? Number(process.env.DB_PORT) : 5432,
      database,
      user: process.env.DB_USER,
      password: await currentPassword(),
      ssl: { rejectUnauthorized: false },
      connectionTimeoutMillis: 10_000,
    })
    try {
      await client.connect()
      await client.end()
      checked.push({ database, connected: true })
    } catch (err) {
      checked.push({ database, connected: false, error: (err as Error).message })
    }
  }

  const leaked = checked.filter((c) => c.connected)
  if (leaked.length) {
    throw new Error(
      `AISLAMIENTO ROTO: ${process.env.DB_USER} pudo conectarse a ${leaked
        .map((l) => l.database)
        .join(', ')}`,
    )
  }
  return { ok: true, usuario: process.env.DB_USER, checked }
}

/** La misma contraseña que usa el pool de la app, desde Secrets Manager. */
async function currentPassword(): Promise<string> {
  const arn = process.env.DB_SECRET_ARN
  if (!arn) return process.env.DB_PASSWORD ?? ''
  const { GetSecretValueCommand, SecretsManagerClient } = await import(
    '@aws-sdk/client-secrets-manager'
  )
  const sm = new SecretsManagerClient({})
  const secret = await sm.send(new GetSecretValueCommand({ SecretId: arn }))
  return (JSON.parse(secret.SecretString ?? '{}') as { password?: string }).password ?? ''
}

/**
 * Loads a data-only SQL dump (made by scripts/load-data.sh from a local
 * database) into an environment that has the schema but no data yet.
 *
 * Refuses to run on a database that already holds projects: this is for the
 * first load, not a sync, and running it twice would duplicate or clash.
 * The dump is deleted from S3 afterwards, whatever the outcome — it holds
 * private data and has no reason to outlive the load.
 */
/** Orden de borrado: hijos antes que padres. */
// Todo menos catálogos y usuarios. historial / solicitudes_cambio no tienen
// FK a proyectos/permisos (entidad_id polimórfico): sin vaciarlas quedarían
// apuntando a ids que ya no existen. Orden: hijos antes que padres.
const WIPE_TABLES = [
  'permisos_comite', 'adjuntos', 'historial', 'solicitudes_cambio',
  'permisos', 'proyectos', 'titulares', 'empresas', 'comites',
]

/**
 * Vacía las tablas de datos (no los catálogos, no `usuarios`) para poder
 * correr `load-data` de nuevo sobre un ambiente que ya tenía algo cargado.
 *
 * DELETE en orden de dependencia, nunca TRUNCATE ... CASCADE: CASCADE de
 * TRUNCATE se lleva puesta CUALQUIER tabla que tenga una FK apuntando a la
 * que se vacía, sin importar si hay filas relacionadas de verdad — vació
 * `usuarios` (que solo tiene una FK hacia `empresas`) la primera vez que
 * corrió esto, borrando el admin de dev por accidente. DELETE en orden
 * respeta las FK y, si algo externo referencia una fila real (por ejemplo
 * un usuario con `empresa_id` apuntando a una empresa que se está por
 * borrar), Postgres corta con un error en vez de arrasar en silencio.
 *
 * No toca `historial` ni `solicitudes_cambio`: no tienen FK real a
 * proyectos/permisos (`entidad_id` es polimórfico — ver
 * `src/db/schema/historial.ts`), así que un wipe no las puede arrastrar ni
 * en cascada ni por error; si tuvieran filas de antes, quedan huérfanas.
 *
 * Se exige `confirm: true` a propósito: no es algo que deba dispararse por
 * accidente.
 */
async function wipeData(confirm: boolean) {
  if (!confirm) {
    throw new Error(
      'Pasá {"action":"wipe-data","confirm":true} para confirmar. ' +
        'Esto borra TODOS los proyectos, permisos, empresas, comités y sus vínculos de este ambiente.',
    )
  }
  const client = await pool.connect()
  try {
    await client.query('BEGIN')
    for (const table of WIPE_TABLES) {
      await client.query(`DELETE FROM ${table}`)
      await client.query(`SELECT setval(pg_get_serial_sequence('public.${table}', 'id'), 1, false)`)
    }
    await client.query('COMMIT')
  } catch (err) {
    await client.query('ROLLBACK').catch(() => undefined)
    throw err
  } finally {
    client.release()
  }
  return status()
}

/**
 * Runs a SQL file from the environment's bucket, in one transaction, on a
 * database that may already have data. For the files generated by
 * db/seed_catalogos.py and db/cargar_excel.py: those only contain
 * INSERT ... ON CONFLICT (add or update by natural key), resolve every
 * reference by name / code instead of by numeric id, and never set ids by
 * hand for data tables — so no sequence juggling is needed afterwards
 * (seed_catalogos.py fixes its own sequences). The file is deleted from S3
 * whether it succeeded or not.
 */
async function applySql(key: string) {
  if (!key?.startsWith('ops/')) throw new Error('key must be under ops/')
  const bucket = process.env.S3_BUCKET_ADJUNTOS
  if (!bucket) throw new Error('S3_BUCKET_ADJUNTOS is not set')
  s3 ??= new S3Client({})

  try {
    const object = await s3.send(new GetObjectCommand({ Bucket: bucket, Key: key }))
    const sql = await object.Body!.transformToString('utf-8')
    const client = await pool.connect()
    try {
      await client.query('BEGIN')
      await client.query(sql)
      await client.query('COMMIT')
    } catch (err) {
      await client.query('ROLLBACK').catch(() => undefined)
      throw err
    } finally {
      client.release(true)
    }
    return status()
  } finally {
    await s3.send(new DeleteObjectCommand({ Bucket: bucket, Key: key })).catch(() => undefined)
  }
}

async function loadData(key: string) {
  if (!key?.startsWith('ops/')) throw new Error('key must be under ops/')

  const bucket = process.env.S3_BUCKET_ADJUNTOS
  if (!bucket) throw new Error('S3_BUCKET_ADJUNTOS is not set')
  s3 ??= new S3Client({})

  try {
    const existing = (await pool.query('SELECT count(*)::int AS n FROM public.proyectos')).rows[0].n
    if (existing > 0) {
      throw new Error(`The database already has ${existing} projects; load-data only runs on an empty one`)
    }

    const object = await s3.send(new GetObjectCommand({ Bucket: bucket, Key: key }))
    const sql = await object.Body!.transformToString('utf-8')

    const client = await pool.connect()
    try {
      await client.query('BEGIN')
      await client.query(sql)
      // Rows keep their original ids, so move each sequence past them or the
      // next INSERT from the app collides with an existing id.
      for (const table of DATA_TABLES) {
        await client.query(
          `SELECT setval(pg_get_serial_sequence('public.${table}', 'id'),
                         GREATEST((SELECT COALESCE(max(id), 0) FROM public.${table}), 1),
                         (SELECT count(*) > 0 FROM public.${table}))`,
        )
      }
      await client.query('COMMIT')
    } catch (err) {
      await client.query('ROLLBACK').catch(() => undefined)
      throw err
    } finally {
      // The dump may have changed session settings; never hand this
      // connection back to the pool.
      client.release(true)
    }

    return status()
  } finally {
    await s3.send(new DeleteObjectCommand({ Bucket: bucket, Key: key })).catch(() => undefined)
  }
}

/**
 * The `usuarios` half of the very first admin of an environment. The Cognito
 * half (the account itself) is created by scripts/create-admin.sh with the
 * AWS CLI, which then passes the account's `sub` here. Every later user is
 * created from the app.
 */
async function createAdmin({ sub, email, nombre }: { sub: string; email: string; nombre: string }) {
  if (!sub || !email || !nombre) throw new Error('sub, email and nombre are required')

  const { rows } = await pool.query(
    `INSERT INTO usuarios (cognito_sub, nombre, email, rol, created_by, updated_by)
     VALUES ($1, $2, $3, 'admin', 'bootstrap', 'bootstrap')
     ON CONFLICT (cognito_sub) DO UPDATE
       SET rol = 'admin', nombre = EXCLUDED.nombre, email = EXCLUDED.email,
           empresa_id = NULL, organismo_id = NULL, region_id = NULL,
           updated_by = 'bootstrap'
     RETURNING id, nombre, email, rol`,
    [sub, nombre, email],
  )
  return rows[0]
}
